Typos in a couple of READMEs
w3c-ccg/traceability-vocab pull request #140
Opened 2021-03-09 14:09 UTC by nissimsan

2021-03-09 15:55 UTC, OR13 approved these changes

2021-03-09 15:57 UTC, TallTed commented on packages/traceability-schemas/README.md
> +Schemas should be named simply, and defined at a high a level as is reasonable.  Words such as 'credential' are redundant and should not be included in schema names.  e.g. a good schema name is `Prod
```suggestion
Schemas should be named simply, and defined at a high a level as is reasonable.  Words such as 'credential' are redundant and should not be included in schema names.  For instance, a good schema name for a type that represents data about a "product" is `Product`; a BAD example would be `ProductCredential`.  A good sub-type that extends `Product` with properties specific to some certain market would be `OrganicProduct`, assuming that an `OrganicProduct` had some specific attributes that are not represented in `Product`.  If the parent type accurately describes all attributes that are required, then a sub-type should not be created. If the only difference is a need to specify that the item is some specific "type" (in human english language meaning) of "Organic Product", then consideration should be given to adding a field to `Product` that specifies the "product type", such as `Product.productType`.  This prevents duplicate redundant objects and allows for sane querying and business rules handling of common objects. 
```

2021-03-09 16:21 UTC, mprorock requested changes
showing some conflicts that need resolving.

2021-03-10 07:33 UTC, nissimsan reviewed
Cool.

2021-03-10 11:49 UTC, mprorock approved these changes

2021-03-10 11:50 UTC, merged