Feat/property arrays
w3c-ccg/traceability-vocab pull request #210
Opened 2021-10-19 16:09 UTC by rhofvendahl

This PR changes the build process to make `classProperty` values arrays of properties, rather than a mix of individual properties and arrays. The purpose of this is to handle cases where multiple properties share the same comment ID, and so would be set to the same `classProperty` key (see: [issue 88](https://github.com/w3c-ccg/traceability-vocab/issues/88)). The previous change supporting mixes of individual properties and arrays addressed this as well, but required array checks across the build pipeline (that hadn't yet been implemented, see: [issue 205](https://github.com/w3c-ccg/traceability-vocab/issues/205)).

This PR depends on changes to transmute-industries/verifiable-data (see: [PR 86](https://github.com/transmute-industries/verifiable-data/pull/86)). Instructions for testing:
- Clone or set up remote for `https://github.com/mesur-io/verifiable-data` & checkout the `feat/property-arrays` branch
- Navigate to `verifiable-data/packages/jsonld-schema` & execute `npm run build`
- Clone or set up remote for `https://github.com/mesur-io/traceability-vocab` & checkout the `feat/property-arrays` branch
- In `traceability-vocab/packages/traceability-schemas/package.json` change `"@transmute/jsonld-schema": "0.0.4-unstable.16",` to `"@transmute/jsonld-schema": "file:~/verifiable-data/packages/jsonld-schema",`
- In `traceability-vocab/packages/traceability-schemas` run `npm install`
- In `traceability-vocab/packages/traceability-schemas` run `npm run build:all` as well as `npm run test` to check for any issues

2021-11-02 17:46 UTC, OR13 requested changes
CI on fork is failing, evidence of passing CI must be obtained before merging.

2021-11-02 17:47 UTC, mprorock requested changes
[CI Failing](https://github.com/mesur-io/traceability-vocab/runs/4083586657?check_suite_focus=true) 

This needs to resolve before we can merge:

```
traceability-schemas: /home/runner/work/traceability-vocab/traceability-vocab/packages/traceability-schemas/scripts/getContextFromIntermediate.js:6
traceability-schemas:   return jsonldSchema.intermediateToContext(intermediate, version, rootTerms);
traceability-schemas:                       ^
traceability-schemas: TypeError: jsonldSchema.intermediateToContext is not a function
traceability-schemas:     at getContextFromIntermediate (/home/runner/work/traceability-vocab/traceability-vocab/packages/traceability-schemas/scripts/getContextFromIntermediate.js:6:23)
traceability-schemas:     at Object.<anonymous> (/home/runner/work/traceability-vocab/traceability-vocab/packages/traceability-schemas/scripts/build-context.js:8:17)
traceability-schemas:     at Module._compile (internal/modules/cjs/loader.js:999:30)
traceability-schemas:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
traceability-schemas:     at Module.load (internal/modules/cjs/loader.js:863:32)
traceability-schemas:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
traceability-schemas:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
traceability-schemas:     at internal/main/run_main_module.js:17:47
```

2021-11-05 21:14 UTC, rhofvendahl commented
It looks like there's a merge conflict with main. A few weeks ago @OR13 added in an `'@vocab'` property to [getContextFromIntermediate](https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/scripts/getContextFromIntermediate.js), which is combined with `partialContext` and some other info to generate the context. This was not compatible with the change in this branch outsourcing context generation to jsonld-schema.

To resolve this I created [PR 111](https://github.com/transmute-industries/verifiable-data/pull/111) in transmute-industries/verifiable-data, which if accepted would define a `schemasToPartialContext` function that would allow this branch's `getContextFromIntermediate` to generate its own context with whatever additional terms it would like.

Once jsonld-schema is updated I'll then need to push another commit to this branch updating package.json to specify the appropriate version for jsonld-schema, after which this PR should be ready for review.

2021-11-09 18:42 UTC, mprorock approved these changes

2021-11-09 18:42 UTC, mprorock commented
@OR13 can you re-review so we can merge if changes are addressed

2021-11-11 14:41 UTC, OR13 approved these changes

2021-11-11 14:41 UTC, OR13 commented
@mprorock @rhofvendahl feel free to merge

2021-11-16 14:40 UTC, OR13 approved these changes

2021-11-16 14:40 UTC, OR13 commented
open fo 5 days, no objections, merging.

2021-11-16 14:40 UTC, merged