USMCA Certificate of Origin
w3c-ccg/traceability-vocab pull request #223
Opened 2021-12-01 12:03 UTC by nissimsan

COO schema for USMCA trade agreement: https://trade.cbp.gov/USMCA/s/
The schema is directly adapted from FedEx's form: https://www.fedex.com/content/dam/fedex/us-united-states/International/upload/FedEx_USMCA_T-MEC_CUSMA_Fillable_Form.pdf

2021-12-01 16:09 UTC, TallTed commented on packages/traceability-schemas/schemas/Person.json
> +            "description": "The Tax / Fiscal ID of the organization or person, e.g. the TIN in the US or the CIF/NIF in Spain.",
```suggestion
            "description": "The Tax / Fiscal ID of the organization or person, e.g., the TIN in the US or the CIF/NIF in Spain.",
```

2021-12-01 16:09 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "Importer, Exporter or Producer Certification of Origin: Indicate whether the certifier is the exporter, producer or importer in accordance with Chapter 5, Article 5.2 (Claims fo
```suggestion
      "description": "Importer, Exporter, or Producer Certification of Origin: Indicate whether the certifier is the exporter, producer, or importer in accordance with Chapter 5, Article 5.2 (Claims for Preferential Tariff Treatment) of the agreement.",
```

2021-12-01 16:10 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "Certifier’s name, address, country, e-mail address, telephone number and tax id.",
```suggestion
      "description": "Certifier’s name, address, country, e-mail address, telephone number, and tax ID.",
```

2021-12-01 16:10 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "Exporter’s name, address (including country), email address and telephone number, if different than the certifier. This information is not required if the producer is completing
```suggestion
      "description": "Exporter’s name, address (including country), email address, and telephone number, if different than the certifier. This information is not required if the producer is completing the Certification of Origin and does not know the identity of the exporter. The address of the exporter shall be the place of export of the good in a Party’s territory. ",
```

2021-12-01 16:11 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "Producer’s name, address (including country), email address and telephone number, if different than the certifier or exporter, or if there are multiple producers, state “Various
```suggestion
      "description": "Producer’s name, address (including country), email address, and telephone number, if different than the certifier or exporter, or, if there are multiple producers, state 'Various' or provide a list of producers. A person that wants this information to remain confidential may state 'Available upon request by the importing authorities.' The address of a producer shall be the place of production of the good in a Party's territory.",
```

2021-12-01 16:12 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "A person that wants the producer information to remain confidential may state “Available upon request by the importing authorities.",
```suggestion
      "description": "A person that wants the producer information to remain confidential may state 'Available upon request by the importing authorities.'",
```

2021-12-01 16:12 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "Importer’s name, address, email address and telephone number (if known). The address of the importer shall be in a Party’s territory. If the identity of the importer is unknown,
```suggestion
      "description": "Importer’s name, address, email address, and telephone number (if known). The address of the importer shall be in a Party's territory. If the identity of the importer is unknown, or there are various importers, please check the appropriate box.",
```

2021-12-01 16:12 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaCertificateOfOrigin.json
> +      "description": "If the identity of the importer is unknown, or there are various importer’s, please check the appropriate box.",
```suggestion
      "description": "If the identity of the importer is unknown, or there are various importers, please check the appropriate box.",
```

2021-12-01 16:14 UTC, TallTed commented on packages/traceability-schemas/schemas/UsmcaProductSpecifier.json
> +      "description": "Specify the Origin Criterion under which the good qualifies, as set out in Chapter 4, Article 4.2 (Originating Goods) of the USMCA/T-MEC/CUSMA agreement (https://ustr.gov/sites/
```suggestion
      "description": "Specify the Origin Criterion under which the good qualifies, as set out in Chapter 4, Article 4.2 (Originating Goods) of the USMCA/T-MEC/CUSMA agreement (https://ustr.gov/sites/default/files/files/agreements/FTA/USMCA/Text/04-Rules-of-Origin.pdf). Criterion A: The good is wholly obtained or produced entirely in the territory of one or more of the USMCA/T-MEC/CUSMA countries, as defined in Article 4.3 of the Agreement; Criterion B: The good is produced entirely in the territory of one or more of the USMCA/T-MEC/CUSMA countries using non-originating materials, provided the good satisfies all applicable requirements of product-specific rules of origin; Criterion C: The good is produced entirely in the territory of one or more of the USMCA/T-MEC/CUSMA countries exclusively from originating materials; or Criterion D: The good is produced entirely in the territory of one or more of the USMCA/T-MEC/CUSMA countries. It is classified with its materials, or satisfies the 'unassembled goods' requirement, and meets a regional value content threshold of not less than 60% if the transaction value method is used, or not less than 50% if the net cost method is used (not including RVC for autos); except for goods in Chapter 61-63 of the HTS.",
```

2021-12-01 16:16 UTC, TallTed requested changes
Minor punctuation, mostly.

2021-12-03 12:07 UTC, nissimsan commented
Good stuff @TallTed - thanks! These were all spelling mistakes copied from fedex. :)

2021-12-07 18:58 UTC, OR13 approved these changes

2021-12-07 18:59 UTC, mprorock approved these changes

2021-12-07 19:01 UTC, merged