feat: added samples and descriptions, aligned to Agr structuring
w3c-ccg/traceability-vocab pull request #225
Opened 2021-12-03 11:24 UTC by nissimsan

2021-12-03 17:13 UTC, TallTed commented on docs/index.html
> +                of consignment contract and c) title of goods.
```suggestion
                of consignment contract, and c) title of goods. 
```

2021-12-07 19:01 UTC, mprorock approved these changes
this is a great enhancement! thanks @nissimsan

2021-12-07 19:04 UTC, OR13 requested changes
please address merge conflicts

2021-12-10 18:53 UTC, OR13 approved these changes

2021-12-14 16:14 UTC, mkhraisha approved these changes

2021-12-14 18:58 UTC, OR13 approved these changes

2021-12-14 18:59 UTC, merged