IATA air waybill
w3c-ccg/traceability-vocab pull request #229
Opened 2021-12-13 21:43 UTC by nissimsan

Updated IATA Air Waybill, based on IATA Air Waybill Resolution 600a https://www.iata.org/contentassets/e9cb5a72b88f4f68a5cfc572a50b60c9/eacph-european-air-cargo-programme-handbook.pdf

Example based on: 
![house-air-waybill-ex](https://user-images.githubusercontent.com/34443212/145893353-86930c20-41a8-49ed-bb26-eda4b1761cd8.png)

2021-12-13 21:55 UTC, OR13 approved these changes

2021-12-13 22:26 UTC, TallTed requested changes
Minor nits

2021-12-13 22:26 UTC, TallTed commented on packages/traceability-schemas/schemas/ChargeDeclaration.json
> +            "description": "The total of all the charges, i.e. weight/volume charge, valuation charge, other charges due carrier and agent and, if applicable, tax. Box 30A and 30B.",
```suggestion
            "description": "The total of all the charges, i.e., weight/volume charge, valuation charge, other charges due carrier and agent, and, if applicable, tax. Box 30A and 30B.",
```

2021-12-13 22:26 UTC, TallTed commented on packages/traceability-schemas/schemas/ConsignmentRatingDetail.json
> +      "description": "This box shall be completed as follows: when a specific commodity rate applies, the IATA item description number shall be inserted on the “C” or “U” rate class line; when a clas
```suggestion
      "description": "This box shall be completed as follows: when a specific commodity rate applies, the IATA item description number shall be inserted on the “C” or “U” rate class line; when a class rate reduction applies, the percentage which is applied to the appropriate charge or rate shall be inserted on the “R” rate class line, preceded by the rate class code to which it refers, e.g., 33% reduction on the normal rate shall be expressed as N67; when a class rate surcharge applies, the percentage which is applied to the appropriate charge or rate shall be inserted on the “S” rate class line, preceded by the rate class code to which it refers, e.g., 50% surcharge of the minimum charge shall be expressed as M150; when a unit load device rate applies, the ULD rate class type used shall be inserted on the “X” rate class line. Box 22E.",
```

2021-12-13 22:26 UTC, TallTed commented on packages/traceability-schemas/schemas/ConsignmentRatingDetail.json
> +      "enum": ["M—minimum charge", "N—normal rate", "Q—quantity rate", "B—basic charge (optional use)", "K—rate per kilogram (optional use)", "P—international priority service rate", "C—specific comm
```suggestion
      "enum": ["M—minimum charge", "N—normal rate", "Q—quantity rate", "B—basic charge (optional use)", "K—rate per kilogram (optional use)", "P—international priority service rate", "C—specific commodity rate", "R—class rate reduction", "S—class rate surcharge", "U—unit load device basic charge or rate", "E—unit load device additional rate", "X—unit load device additional information", "Y—unit load device discount", "W—weight increase"]
```

2021-12-13 22:26 UTC, TallTed commented on packages/traceability-schemas/schemas/ForeignChargeDeclaration.json
> +            "description": "The amount shown in the “Total Collect” box shall be inserted after conversion to the foreign currency. Box 33B.",
```suggestion
            "description": "The amount shown in the \"Total Collect\" box shall be inserted after conversion to the foreign currency. Box 33B.",
```

2021-12-14 09:27 UTC, nissimsan commented
Excellent catches, @TallTed, especially the enums - appreciated!

2021-12-14 16:10 UTC, mkhraisha approved these changes

2021-12-14 19:12 UTC, mprorock approved these changes

2021-12-14 19:18 UTC, merged