fix: date type
w3c-ccg/traceability-vocab pull request #283
Opened 2022-01-27 12:57 UTC by nissimsan

https://github.com/w3c-ccg/traceability-vocab/issues/213#issuecomment-1021340062

2022-01-27 13:44 UTC, mprorock approved these changes

2022-02-01 18:47 UTC, OR13 commented on docs/openapi/components/schemas/common/IATAAirWaybillCertificate.yml
> +      '@type': http://www.w3.org/2001/XMLSchema#dateTime
```suggestion
       '@type': http://www.w3.org/2001/XMLSchema#dateTime     
```

2022-02-01 18:47 UTC, OR13 requested changes
Please fix whitespacing.

2022-02-02 14:29 UTC, OR13 approved these changes

2022-02-08 18:47 UTC, OR13 approved these changes

2022-02-08 18:47 UTC, merged