feat: improved scenarios
w3c-ccg/traceability-vocab pull request #305
Opened 2022-02-09 20:41 UTC by nissimsan

2022-02-10 14:29 UTC, mprorock approved these changes

2022-02-15 17:10 UTC, TallTed requested changes
Mostly whitespace to improve source readability. Some punctuation and the like.

2022-02-15 17:10 UTC, TallTed commented on docs/index.html
> +          The Chinese Manufacturer receives an order from their Danish customer (2). An invoice is issued (3) and presented back to customer (4).
```suggestion
A Danish Vendor has received an online order, issues a Purchase Order (1)
which is presented to the Chinese manufacturer for fulfillment (2). 
          </p>
        <p> 
The Chinese Manufacturer receives an order from their Danish customer (2).
An invoice is issued (3) and presented back to customer (4). 
```

2022-02-15 18:38 UTC, OR13 approved these changes
I am ok with these changes @nissimsan please accept for reject @TallTed 's suggestions.

2022-02-18 12:58 UTC, nissimsan commented
Thanks, @TallTed - keeping me on the straight'n'narrow! :)

2022-02-22 18:56 UTC, merged