fix: clean up openapi yaml files
w3c-ccg/traceability-vocab pull request #317
Opened 2022-02-27 03:03 UTC by rhofvendahl

This PR cleans up a number of minor issues with the YAML schema files.

Of these changes, a few are pretty much guesses and definitely need review:
- There were a handful of examples where additional properties were passed to entities with `additionalProperties: false` (often "ID" to Organization instances). I chose to remove the additional parameters being passed in.
  - in CTPATCertificate.yml
  - in DCSATransportDocument.yml
  - in USMCACertifier.yml
- Several example `@context`s listed something like:
  ```
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        {
          "@vocab": "https://w3id.org/traceability/v1/vocab#"
        }
      ],
  ```
  which conflicted with `@context` defined as a const:
  ```
    '@context':
      type: array
      const:
        - 'https://www.w3.org/2018/credentials/v1'
        - 'https://w3id.org/traceability/v1'
  ```
  In these cases I changed the example `@context` to:
  ```
      "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
  ```
- A few schemas were missing `$linkedData`. I filled these in with best guesses:
  - Context.yml
  - TraceablePresentation.yml
  - Workflow.yml
- In one case a `$linkedData` was similarly missing from a property:
  - SIMASteelImportLicenseApplication.yml (`productInformation` property)
- In Transport.yml there were two required properties that weren't actually present as properties, which I removed.

(Changes I'm more confident about not mentioned)

2022-02-27 04:45 UTC, rhofvendahl commented
Update: For some reason the "Verifiable Credentials" test in credentials.sanity.test.js only passes when I revert CTPATCertificate.yml to include IDs for issuer and credentialSubject. As ID is not a property defined in the Organization schema (which those properties reference) and Organization does not allow additional properties, this triggers a console.error message.

I'll leave the IDs in so the test passes, but if anyone has any suggestions I'd love to hear them.

2022-02-28 22:01 UTC, nissimsan commented
@rhofvendahl, again: thanks!! 

> In these cases I changed the const to:
> ```
>   const:
>     - 'https://www.w3.org/2018/credentials/v1'
>     - '@vocab': 'https://w3id.org/traceability/v1/vocab#'
> ```
... [As mentioned](https://github.com/w3c-ccg/traceability-vocab/pull/316#issuecomment-1054645050) these `@vocab`s shouldn't survive. 

Our fixes to TraceablePresentation.yml and Workflow.yml seems largely identical. 

I refactored the SIMA licences a fair bit today.

2022-03-01 18:52 UTC, OR13 requested changes
the syntax is not correct, `@vocab` should probably not be added like this.

2022-03-07 16:30 UTC, nissimsan commented
@rhofvendahl , we still stick with the order discussed last week (and [here](https://github.com/w3c-ccg/traceability-vocab/pull/316#issuecomment-1053015906)), right: 
- First merge https://github.com/w3c-ccg/traceability-vocab/pull/319
- Then adjust [this](https://github.com/w3c-ccg/traceability-vocab/pull/317)

2022-03-07 18:22 UTC, mkhraisha approved these changes
Looks reasonable, but I haven't actually tested these. 
@OR13 would you be able to do a sanity check on this?

2022-03-08 18:51 UTC, mprorock approved these changes

2022-03-15 17:57 UTC, mkhraisha commented
`@vocab` pr has been merged, this needs conflict fixes and should be good to go.

2022-03-22 15:57 UTC, OR13 requested changes
Conflicts and change requests need to be addressed,  suggest merging https://github.com/w3c-ccg/traceability-vocab/pull/355 before this one.

2022-03-29 17:20 UTC, closed without merging