chore: white-space change for testing
w3c-ccg/traceability-vocab pull request #323
Opened 2022-03-01 17:26 UTC by BenjaminMoe

2022-03-01 18:59 UTC, OR13 approved these changes

2022-03-07 16:38 UTC, nissimsan requested changes
@BenjaminMoe, wonderful that you are adding documentation to the "future tool" on the /data/README.md. But (despite using Purchase Order as the example), that part really has nothing to do with this PR. 
I suggest you split that into a separate PR.

2022-03-07 16:41 UTC, BenjaminMoe commented
@nissimsan Thanks the feedback. I was thinking that separation of concerns could be handled better here. I'll leave this PR up as adding placeholders for the Purchase Order documents, and split the documentation updates into a separate PR.

2022-03-07 18:29 UTC, mkhraisha commented
How is a purchase order significantly different from the existing [Purchase Schema](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/Purchase.yml)? 
Looks like a Purchase wraps a Purchase order, do we want to have both in the vocabulary?

2022-03-08 14:02 UTC, BenjaminMoe commented
A Purchase Order is a pretty common B2B document, where a buyer is requesting goods to be delivered at a certain place, at a certain time, fitting certain conditions. 

For example, in the case of just in time manufacturing, an OEM would order parts from several suppliers on the conditions they are delivered ready to be assembled. 

The Purchase schema, seems to refer to a `purchaseOrder` in the definition. I'm guessing the string is for a PurchaseOrder No., but no example is provided. 

```
  purchaseOrder:
    title: Purchase Order
    description: The purchase order associated with a purchase
    type: string
    $linkedData:
      term: purchaseOrder
      '@id': https://schema.org/identifier
 ```
 
As for PurchaseOrderCertificate, versus PurchaseOrder. This is for conventions. A PurchaseOrder is the document for the good to be purchased, the delivery date, and any other conditions required for payment. A PurchaseOrderCerticiate is verifiable credential signed by a buyer.

2022-03-08 14:06 UTC, BenjaminMoe commented
> @BenjaminMoe, wonderful that you are adding documentation to the "future tool" on the /data/README.md. But (despite using Purchase Order as the example), that part really has nothing to do with this PR. I suggest you split that into a separate PR.

Documentation moved to: https://github.com/w3c-ccg/traceability-vocab/pull/333/files

2022-03-08 16:28 UTC, mkhraisha commented
Are you advocating for both a Purchase Schema and a Purchase Order schema?
If so we probably need a clear line of delineation between them, especially since a Purchase has a purchase order identifier on it. 
I was working under the assumption that a Purchase **is** a Purchase Order, but I may be missing something.

if these are distinct entities, then it may be a good idea to link Purchase Order id from Purchase, which should be in a different PR, just flagging it as a potential issue to be raised.

2022-03-08 18:39 UTC, BenjaminMoe commented
For clarification, yes. A Purchase **is not a** Purchase Order. 
A Purchase is a transaction.
A Purchase Order is a request for goods to be delivered on a certain date, under certain conditions.

I make a Purchase Order to have a number of clothing items delivered to a store. The delivery doesn't make it on time. Thus no Purchase takes place.

2022-03-08 18:44 UTC, mkhraisha approved these changes

2022-03-08 18:52 UTC, mprorock approved these changes

2022-03-08 18:55 UTC, nissimsan approved these changes

2022-03-08 18:57 UTC, merged