Add id and context requirements
w3c-ccg/traceability-vocab pull request #449
Opened 2022-06-17 19:05 UTC by OR13

- Point to the TR
- Define context requirement
- Define `id` requirement

2022-06-20 09:17 UTC, nissimsan approved these changes

2022-06-20 15:38 UTC, TallTed requested changes

2022-06-20 15:38 UTC, TallTed commented on docs/index.html
> +          <p>The object MUST have and <code>id</code> property and it must ba valid IRI (URI, URN).</p>
```suggestion
          <p>The object MUST have an <code>id</code> property, and its value MUST be a valid IRI (URI, URN).</p>
```

2022-06-20 15:38 UTC, TallTed commented on docs/index.html
> +          <p>The object MUST have and <code>id</code> property and it must ba valid IRI (URI, URN).</p>
```suggestion
          <p>The object MUST have an <code>id</code> property, and its value MUST be a valid IRI (URI, URN).</p>
```

2022-06-20 19:13 UTC, nissimsan commented
@OR13, I committed two good suggestions from Ted on your PR.

2022-06-20 19:17 UTC, mkhraisha approved these changes

2022-06-21 15:41 UTC, BenjaminMoe approved these changes

2022-06-21 17:41 UTC, merged