Remove Mill Test Report RDF Type
w3c-ccg/traceability-vocab pull request #457
Opened 2022-06-27 16:12 UTC by BenjaminMoe

Mill test report is only used in one certificate. As it's not a "common" data type it should only be defined in the credential that uses it. This PR merges Mill test Report into the Mill Test Report Certificate.

2022-06-27 18:57 UTC, OR13 approved these changes

2022-06-28 09:13 UTC, mkhraisha requested changes
I fundamentally disagree with this PR.
We have a couple of use cases that use the MillTestReport object as a raw schema without having to use the certificate object of it, is this PR change integral to your workflow or is this intended as cleanup?

2022-06-28 12:35 UTC, BenjaminMoe commented
@mkhraisha This is a PR that is a proof of concept around data modeling. Right now the schema's in the `common` folder are building blocks for credentials. In the case of `Mill Test Report` and `Mill Test Report Certificate`, this is an example where a building block schema is only used in one credential. And this PR provides an example of how these could be merged.

2022-06-28 12:59 UTC, OR13 commented
You should add your use cases to the document. The current document only
has a single credential that uses the MTR RDF class.

On Tue, Jun 28, 2022, 7:35 AM Benjamin Collins ***@***.***>
wrote:

> @mkhraisha <https://github.com/mkhraisha> This is a PR that is a proof of
> concept around data modeling. Right now the schema's in the common folder
> are building blocks for credentials. In the case of Mill Test Report and Mill
> Test Report Certificate, this is an example where a building block schema
> is only used in one credential. And this PR provides an example of how
> these could be merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c-ccg/traceability-vocab/pull/457#issuecomment-1168665237>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB7JLMHOGXDYTCSVL5WYFH3VRLWRDANCNFSM5Z6PY72A>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-06-28 13:59 UTC, vivienfan commented
I went through it and it won't actually affect us, @mkhraisha 
on the other hand, i think this should extend from `InspectionReport`

2022-06-28 14:01 UTC, mkhraisha approved these changes

2022-07-05 17:43 UTC, merged