Legal Entity Identifier
w3c-ccg/traceability-vocab pull request #50
Opened 2020-12-03 23:19 UTC by cstoecker

Verifiable vLEI Credentials & Schemas for Legal Entity Identifier in accordance to GLEIF standards

1. Verifiable Credential Example
2. vLEI Schema based on GLEIF's leiCode: vLEIIdentityCredential (see also [www.schema.org/leiCode](www.schema.org/leiCode))
3. Evidence Document Schema: LEIevidenceDocument

2020-12-04 16:48 UTC, OR13 requested changes
credential is malformed:

```
"verificationMethod": "ECDSADigitalSignature",
```

See https://w3c.github.io/vc-data-model/#proofs-signatures-0

2020-12-06 20:42 UTC, OR13 commented
The rest of this data model looks good

2020-12-08 17:35 UTC, mprorock approved these changes

2020-12-08 19:26 UTC, OR13 approved these changes

2020-12-14 18:22 UTC, merged