Ecomm JSON Schema error fixes
w3c-ccg/traceability-vocab pull request #509
Opened 2022-07-29 13:57 UTC by nissimsan

This fixes JSON Schema errors on Ecommerce certificates. These are the ones which are normally hidden, but emerge on the console when other errors exist.

There are three main category of bugs fixed:

- Array const instead of enum, which has been copy-pasted many times
- Changes to Org and Entity propagating to where referenced
- "Normal", one-off JSON Schema bugs (mostly mine)

2022-08-01 08:53 UTC, nissimsan commented
Btw, this also contains a few LD term fixes.

2022-08-01 13:12 UTC, OR13 commented on docs/openapi/components/schemas/credentials/IATAAirWaybillCertificate.yml
> +          "Entity"
change to Organization

2022-08-01 13:12 UTC, OR13 requested changes
don't use "Entity"

2022-08-01 13:12 UTC, OR13 commented on docs/openapi/components/schemas/common/BillOfLading.yml
> +      "type": ["Entity"],
same comment

2022-08-02 17:31 UTC, mprorock approved these changes

2022-08-02 18:07 UTC, nissimsan commented
Merging out of call when changed back to Org

2022-08-03 12:18 UTC, nissimsan commented
@OR13, doubled down changing Organization to Entity everywhere now. Merging.

2022-08-03 12:18 UTC, merged

2022-08-03 16:20 UTC, TallTed commented
> [@nissimsan] @OR13, doubled down changing Organization to Entity everywhere now. Merging.

Looking at a couple of the latest commits, I'm pretty sure that should have said ```changing Entity to Organization```

2022-08-04 19:52 UTC, nissimsan commented
@TallTed, aargh - yes, absolutely!! 🤦‍♂️