Added missing mech properties
w3c-ccg/traceability-vocab pull request #563
Opened 2022-09-16 09:19 UTC by nissimsan

MTR was missing mech property examples

2022-09-20 18:06 UTC, mkhraisha requested changes

2022-09-20 18:06 UTC, mkhraisha commented on docs/openapi/components/schemas/credentials/MillTestReportCertificate.yml
> +                "identifier": "ISO 1352:2021",
https://github.com/w3c-ccg/traceability-vocab/blob/e92bb49a71b74c3d05fe75dc76ef1e99fdde3d80/docs/openapi/components/schemas/common/SteelProduct.yml#L119
These seem to have a minor difference in them, probably a good idea for them to be identical

2022-09-20 18:06 UTC, mkhraisha commented on docs/openapi/components/schemas/credentials/MillTestReportCertificate.yml
> +                "identifier": "ISO 1519:2011",
This one does not exist on the steel product

2022-09-20 18:09 UTC, brownoxford commented
Consensus on call to fix and merge when ready

2022-09-20 18:09 UTC, nissimsan commented
I'll remove the package lock before merging

2022-09-21 06:30 UTC, nissimsan commented
@mkhraisha, I've copied the examples from SteelProduct now instead as you suggest. Made a separate PR to avoid git acrobatics: https://github.com/w3c-ccg/traceability-vocab/pull/580

2022-09-21 06:31 UTC, closed without merging