Rename organic certificate & certificate credential
w3c-ccg/traceability-vocab pull request #602
Opened 2022-10-25 18:18 UTC by rhofvendahl

This PR renames organic certificate to organic credential.

2022-10-27 08:22 UTC, BenjaminMoe requested changes
For credentials, can you add the required fields to the schema?

```
required:
  - '@context'
  - type
  - issuanceDate
  - issuer
  - credentialSubject
```

Link to example: https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/credentials/BillOfLadingCredential.yml#L67

2022-10-31 17:39 UTC, mkhraisha approved these changes

2022-10-31 19:24 UTC, rhofvendahl commented
@BenjaminMoe This is fixed

2022-10-31 21:25 UTC, BenjaminMoe approved these changes

2022-11-01 10:36 UTC, nissimsan approved these changes

2022-11-01 17:42 UTC, BenjaminMoe commented
Merge once merge have been addressed, go ahead and merge.

2022-11-04 19:44 UTC, merged