Add plant systems inspection
w3c-ccg/traceability-vocab pull request #603
Opened 2022-10-26 01:27 UTC by rhofvendahl

This PR adds schemas for plant systems inspection as well as a corresponding credential.

For reference:
[Plant Systems Audits](https://www.ams.usda.gov/services/auditing/plant-audits)
[Example audit sheet](https://www.ams.usda.gov/sites/default/files/media/Sample_Audit_Report%5B1%5D.pdf)
[Inspector reference manual](https://www.ams.usda.gov/sites/default/files/media/Plant_Systems_Audit_Program_Manual%5B1%5D.pdf)

2022-10-27 20:25 UTC, nissimsan approved these changes

2022-10-31 12:57 UTC, BenjaminMoe approved these changes

2022-10-31 13:06 UTC, BenjaminMoe requested changes
`PlantSystemsInspection`, `PlantSystemsQuestion` should use the following format for `type`. 

```
    type: array
    readOnly: true
    const:
      - PlantSystemsInspection
    default:
      - PlantSystemsInspection
    items:
      type: string
      enum:
        - PlantSystemsInspection
```

2022-10-31 17:40 UTC, mkhraisha approved these changes

2022-10-31 21:25 UTC, BenjaminMoe approved these changes

2022-11-01 17:43 UTC, BenjaminMoe commented
Okay to merge out of meeting once merge conflicts have been addressed.

2022-11-04 00:07 UTC, merged