Create PPQ 368 form
w3c-ccg/traceability-vocab pull request #620
Opened 2022-11-11 07:56 UTC by rhofvendahl

This PR creates a schema for PPQ 368, Notice of Arrival form.

2022-11-11 09:14 UTC, nissimsan requested changes

2022-11-11 09:14 UTC, nissimsan commented on docs/openapi/components/schemas/common/PPQ368NoticeOfArrival.yml
> +description: PPQ 368, Notice of Arrival, is to be prepared by a permittee or their agent immediately upon arrival, for submission to the PPQ office having jurisdiction over the port of arrival.
Please spell out what PPQ means (Plant Protection and Quarantine)

2022-11-11 09:14 UTC, nissimsan commented on docs/openapi/components/schemas/common/PPQ368NoticeOfArrival.yml
> +  term: PPQ368NoticeOfArrival
Typically we prefix with the schema authority. I wonder if we could include that here too - USDA, I suppose?

2022-11-11 16:53 UTC, nissimsan approved these changes

2022-11-15 19:01 UTC, BenjaminMoe approved these changes

2022-11-15 19:01 UTC, brownoxford approved these changes

2022-11-18 01:31 UTC, merged