406-fibo-finance
w3c-ccg/traceability-vocab pull request #647
Opened 2022-11-30 23:08 UTC by fkim7

2022-12-06 15:46 UTC, BenjaminMoe requested changes
Looks like there are some errors with the CI. https://github.com/w3c-ccg/traceability-vocab/actions/runs/3593988961/jobs/6118985939

Edit: we can help with tooling if you have any questions.

2022-12-06 18:17 UTC, TallTed commented on docs/openapi/components/schemas/common/BankAccount.yml
> +    description: Business Identifier Code- ISO 9362 identification of the financial institution’s branch.
```suggestion
    description: Business Identifier Code — ISO 9362 identification of the financial institution’s branch.
```

2022-12-06 18:17 UTC, TallTed commented on docs/openapi/components/schemas/common/BankAccount.yml
> +    description: International Bank Account Number- ISO 13616 identification of bank accounts across national borders.
```suggestion
    description: International Bank Account Number — ISO 13616 identification of bank accounts across national borders.
```

2022-12-06 18:36 UTC, nissimsan commented
@fkim7 , we're discussing this on the call. We are happy to help get the issue resolved. You are also very welcome to join the weekly call. 
COntent looks good - we'd love to merge this.

2022-12-06 19:29 UTC, fkim7 commented
Yes I saw the invalid IRI- Where can I put the content of https://knox-networks.github.io/schema/bankaccount/v1.jsonld ?

2022-12-12 12:30 UTC, BenjaminMoe approved these changes
Looks like this is from a fork. I'd be okay with merging this if we make an issue to address an CI issue after merge.

2022-12-13 15:18 UTC, fkim7 commented
> > Yes I saw the invalid IRI- Where can I put the content of https://knox-networks.github.io/schema/bankaccount/v1.jsonld ?
> 
> You can put the content of the `context` json, in here: https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/services/contexts.js#L23

Thank you! Updated context to be under https://w3id.org/traceability/v1 and updated the file name under /credential

Can someone review and approve & merge if all looks good?

2022-12-13 17:10 UTC, BenjaminMoe commented
> Can someone review and approve & merge if all looks good?

@fkim7, we'll review it on the call in an about an hour which you're welcome to come if you want to attend: https://github.com/w3c-ccg/traceability-vocab#meetings

2022-12-13 18:57 UTC, nissimsan commented
Merging, @BenjaminMoe , please fix the CI issues subsequently

2022-12-13 18:57 UTC, merged