E-Commerce use case
w3c-ccg/traceability-vocab pull request #66
Opened 2021-01-27 19:34 UTC by bumblefudge

Added to intro section

2021-01-27 22:05 UTC, TallTed commented on docs/index.html
> +            individual packages with the pre-registration of commercial products
```suggestion
            quite hard to combine usefully. Linking the registration of individual
            packages together with the pre-registration of commercial products
```

2021-01-27 22:09 UTC, TallTed commented on docs/index.html
> +            already adopted today. We distinguish between the VCs that are
```suggestion
            ontology work of GS1 (GTINs and vLEIs), and with shipping and 
            tracking semantics already adopted today by international
            logistics consortia. We distinguish between the VCs that are
```

2021-01-27 22:59 UTC, bumblefudge commented
thanks for the edits @TallTed !

2021-01-29 01:50 UTC, mprorock requested changes

2021-01-29 01:50 UTC, mprorock commented on docs/index.html
> +            <a
any reason for the whitespace changes outside of the core e-commerce section?  looks like a formatter may have kicked in or something.  Mind backing out all changes except for the direct changes to your section on e-commerce?  at that point i will go ahead and merge

2021-01-30 19:52 UTC, mprorock approved these changes

2021-01-30 19:52 UTC, merged