Update Intent to Import
w3c-ccg/traceability-vocab pull request #674
Opened 2022-12-15 19:31 UTC by ipbyrne

This PR is for updating the Intent to Import Credential required fields and examples.

2022-12-15 19:38 UTC, TallTed commented
Please update the title of this PR to `Update Intent to Import`.
(Current last word is erroneously `Important`.)

2022-12-19 17:28 UTC, BenjaminMoe commented on docs/openapi/components/schemas/common/IntentToImport.yml
> +    $ref: ./Organization.yml
I don't think we want to pull in the whole Organization object. We want to only include a subset of what we want to use. Example here: https://github.com/w3c-ccg/traceability-vocab/blob/intent-to-import/docs/openapi/components/schemas/credentials/MillTestReportCredential.yml#L99

2022-12-19 17:28 UTC, BenjaminMoe commented on docs/openapi/components/schemas/common/IntentToImport.yml
> +    $ref: ./Organization.yml
Same here, declare an object as a subset of organization.

2022-12-19 17:29 UTC, BenjaminMoe requested changes
Request: Narrow definition for organization. You can declare a subset in the `snippets` folder.

2022-12-20 15:53 UTC, BenjaminMoe approved these changes

2022-12-21 10:54 UTC, nissimsan requested changes

2022-12-21 10:54 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/BillOfLadingCredential.yml
> +      "created": "2022-12-20T15:30:19Z",
@ipbyrne, you are re-signing all credentials for no reason. You shouldn't be touching the credentials which aren't actually part of the PR's scope. It makes it hard to understand the actual impact of the PR and causes unnecessary merge conflicts.
Please revert the re-signing of credentials which aren't needed. 
Next time, just run the `regenerate` script, it takes care of all this.

2022-12-21 10:55 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/BillOfLadingCredential.yml
> +      "created": "2022-12-20T15:30:19Z",
Beyond the unnecessary resigns, the PR is great

2022-12-21 14:15 UTC, closed without merging