GS1 gtin8 license credential
w3c-ccg/traceability-vocab pull request #675
Opened 2022-12-21 14:11 UTC by nissimsan

From https://ref.gs1.org/gs1/vc/data-model/

2022-12-21 14:29 UTC, BenjaminMoe approved these changes

2022-12-22 15:21 UTC, TallTed commented on docs/openapi/components/schemas/credentials/GS18PrefixLicenseCredentialyml
> +  A GS1 Prefix is issued by GS1 Global Office and allocated a GS1 Member Organisation or to itself for the purpose of issuing GS1 Company Prefix or GS1 identification key licences.
```suggestion
  A GS1 Prefix is issued by GS1 Global Office and allocated to a GS1 Member Organization or to itself for the purpose of issuing GS1 Company Prefix or GS1 identification key licenses.
```

2022-12-22 15:22 UTC, TallTed commented on docs/openapi/components/schemas/credentials/GS18PrefixLicenseCredentialyml
> +        description: The DID for the GS1 Member Organisation, or GS1 Global Office itself, to whom the GS1-8 Prefix has been licensed.
```suggestion
        description: The DID for the GS1 Member Organization, or GS1 Global Office itself, to which the GS1-8 Prefix has been licensed.
```

2023-01-03 15:49 UTC, mkhraisha requested changes
I think the file extension isn't working? you may have put `yml` instead of `.yml`

2023-01-03 18:43 UTC, nissimsan commented
@nissimsan to merge offline once the file extension bug is fixed.

2023-01-03 18:43 UTC, mkhraisha approved these changes
Assuming Extension changed

2023-01-03 18:55 UTC, paulfdietrich commented
@nissimsan.  I did verify against the data model and this looks correct.

2023-01-05 10:34 UTC, nissimsan commented
Fixed. Good catch, @mkhraisha - thanks!
Merging.

2023-01-05 10:35 UTC, merged