Ag inspection additions
w3c-ccg/traceability-vocab pull request #696
Opened 2023-01-27 01:35 UTC by rhofvendahl

This PR adds a few fields to `AgricultureInspectionGeneric` and updates the types on that same schema.

2023-01-27 13:40 UTC, BenjaminMoe approved these changes

2023-01-30 17:16 UTC, mkhraisha requested changes
Many of the new schemas being pointed to are already defined in the vocabulary, is there a reason we aren't pointing directly to them?

2023-01-30 19:50 UTC, rhofvendahl commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
I've been using the unece relatedObservation for new ag schemas (e.g. PPQ forms), but it's true that prior to that Observation references used @id https://w3id.org/traceability#observation.

I had the impression that external @id's were preferable to traceability properties so I generally look for appropriate properties in e.g. service.unece.org first, and relatedObservation I think fits pretty well. However, I'm open to suggestions here. Could you explain when you think it's appropriate to use traceability property definitions vs external definitions?

2023-01-30 19:54 UTC, rhofvendahl commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#Measurement
This is another place where I've been defaulting to external IDs. With QuantitativeValue though there actually does seem to be a lot of precedent for using more specific external definitions.

2023-01-30 20:05 UTC, TallTed commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
@rhofvendahl — Please revisit your https://github.com/w3c-ccg/traceability-vocab/pull/696#discussion_r1091074112, and wrap each instance of `@id` in code fences. In this case, single backticks will work fine, i.e., ``` `@id` ```. Until you do, that GitHub user will receive notifications of every update to this PR, though they are not participating in the CCG by their own volition.

2023-01-30 20:05 UTC, rhofvendahl commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://www.gs1.org/voc/certificationType
I went with `https://www.gs1.org/voc/certificationType` for a few reasons:
- I've been using properties from the gs1 CertificationDetails class where possible for inspection & certificate properties, in an attempt to keep interrelated properties consistent
- While there is obviously a difference between an inspection and a certificate, inspection type and certificate type generally share the same possible values
- `value` seemed pretty vague, and I certificationType was the best I found as a more specific alternative

That said this definitely isn't a cut-and-dry case, and I'm very open to any opinions or suggestions.

2023-01-30 20:07 UTC, rhofvendahl commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
Ah, thanks Ted!

2023-02-01 19:55 UTC, mkhraisha commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
relatedObservation from that link appears to be relevant to transport related observations? they have defined an observation class directly.

I'm not directly opposed to pointing from here to an external definition of an observation that makes sense. What I'm seeing is you're referring to the traceability observation yaml with its own ID, and then pointing to the uncefact related observation definition. 

if there is no difference between the two definitions of observation, then we should update all our local definitions to point to the uncefact vocabulary, if there are differences then I believe this is an error

2023-02-02 14:02 UTC, OR13 commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
https://w3c-ccg.github.io/traceability-vocab/#Observation is an RDF type.

https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation is an RDF Property

2023-02-13 21:18 UTC, rhofvendahl commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
@mkhraisha would it work for you to change `Observation` property references to `https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation` IFF the property is transport related?

Either way though, I think that's out of scope for this PR. Would you be OK leaving this as `uncefact/#relatedObservation` for this PR?

2023-02-21 04:31 UTC, nissimsan approved these changes

2023-02-28 17:42 UTC, mkhraisha commented on docs/openapi/components/schemas/common/AgricultureInspectionGeneric.yml
> +      '@id': https://service.unece.org/trade/uncefact/vocabulary/uncefact/#relatedObservation
yes

2023-02-28 17:42 UTC, mkhraisha approved these changes

2023-02-28 18:38 UTC, merged