Oil gas product
w3c-ccg/traceability-vocab pull request #720
Opened 2023-03-27 15:31 UTC by vivienfan

crude oil product and natural gas product merge and cleanup

2023-03-27 15:58 UTC, TallTed requested changes

2023-03-27 15:58 UTC, TallTed commented on docs/openapi/components/schemas/common/OilAndGasProduct.yml
> +          "description":"ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introdu
```suggestion
          "description":"ISO 1352:2011 specifies the conditions for performing torsional, constant-amplitude, nominally elastic stress fatigue tests on metallic specimens without deliberately introducing stress concentrations. The tests are carried out at ambient temperature (ideally at between 10°C and 35°C) in air by applying a pure couple to the specimen about its longitudinal axis."
```

2023-03-28 19:53 UTC, nissimsan approved these changes

2023-04-04 16:03 UTC, mkhraisha approved these changes

2023-04-04 17:39 UTC, merged