Fix undefined terms in traceable presentation
w3c-ccg/traceability-vocab pull request #737
Opened 2023-04-13 19:10 UTC by OR13

2023-04-13 19:11 UTC, OR13 commented on packages/traceability-schemas/scripts/openapi-to-context.js
> +          '@vocab': 'https://w3id.org/traceability#'
Maybe you didn't know this was possible, but it is.

2023-04-18 17:31 UTC, mkhraisha requested changes

2023-04-18 17:31 UTC, mkhraisha commented on docs/openapi/components/schemas/presentations/TraceablePresentation.yml
>    - holder
shouldnt there be a required verifiableCredential[] here?

2023-04-18 17:54 UTC, BenjaminMoe approved these changes

2023-04-18 17:58 UTC, mkhraisha approved these changes

2023-04-18 17:59 UTC, merged