Elaboration of organization `id`
w3c-ccg/traceability-vocab pull request #749
Opened 2023-04-20 12:21 UTC by nissimsan

This is an elaboration of what we are expecting as an organization identifier. This isn't obvious, if you aren't already in the RDF mindset.

2023-04-20 17:52 UTC, TallTed requested changes
Minor tweaks.

2023-04-20 17:52 UTC, TallTed commented on docs/openapi/components/schemas/common/Organization.yml
> +    description: Organization identifier. This must be an Internationalized Resource Identifiers such as a DID, URI, URL or URN.
```suggestion
    description: Organization identifier. This must be an Internationalized Resource Identifier such as a DID, URI, URL, or URN.
```

2023-04-20 17:52 UTC, TallTed commented on docs/openapi/components/schemas/credentials/MillTestReportCredential.yml
> +            description: Organization identifier. This must be an Internationalized Resource Identifiers such as a DID, URI, URL or URN.
```suggestion
            description: Organization identifier. This must be an Internationalized Resource Identifier such as a DID, URI, URL, or URN.

```

2023-04-25 17:43 UTC, OR13 approved these changes

2023-04-25 17:52 UTC, merged