Update Syntax for credential Schema
w3c-ccg/traceability-vocab pull request #768
Opened 2023-05-09 13:45 UTC by BenjaminMoe

Syntax sugar updates to `credentialSchema`

- `example` is a placeholder
- `default` implies what the value should be
- `readonly` sets form input to readonly for form libraries that support it

2023-05-09 16:20 UTC, mkhraisha approved these changes

2023-05-09 17:37 UTC, nissimsan approved these changes

2023-05-09 17:38 UTC, OR13 approved these changes

2023-05-09 17:38 UTC, mkhraisha requested changes
Indent issues

2023-05-10 18:30 UTC, mkhraisha approved these changes

2023-05-10 18:30 UTC, merged