Entry number credential
w3c-ccg/traceability-vocab pull request #781
Opened 2023-05-17 13:29 UTC by nissimsan

2023-05-17 15:12 UTC, mprorock approved these changes
This is a good simplification and the pointer to cefact is good

2023-05-17 17:56 UTC, mkhraisha requested changes
Few issues with this idea.

1. By removing Thing we have no way of allowing an identifier that exists on an outside system to be connected to a workflow in a generic way, we are committing to adding many of these smaller credentials. 
2. This removes the ability to add a free trade zone number.

2023-05-17 17:56 UTC, mkhraisha commented on docs/openapi/components/schemas/common/CBPEntrySummary.yml
> +      '@id': https://vocabulary.uncefact.org/ReferenceCodeList#AQM
This is great

2023-05-17 20:01 UTC, nissimsan commented
@mkhraisha, how about I leave ThingCredential untouched and just add EntryNumberCredential (instead of overwriting)?

2023-05-17 20:03 UTC, mkhraisha commented
We could do that or we can all agree on this direction and then I'll add a FTZ no credential.


Regardless I think we may need the thing credential.

2023-05-17 20:08 UTC, TallTed commented on docs/openapi/components/schemas/common/EntryNumber.yml
> +        description: The 11 digit alphanumeric code. The entry number is comprised of the three-digit filer code, followed by the seven-digit entry number, and completed with the one-digit check digi
```suggestion
        description: The 11 digit alphanumeric code. The entry number is comprised of the three-digit filer code, followed by the seven-digit entry number, and completed with the one-digit check digit. The Entry Filer Code represents the three-character alphanumeric filer code assigned to the filer or importer by CBP. The Entry Number represents the seven-digit number assigned by the filer. The number may be assigned in any convenient manner, provided that the same number is not assigned to more than one CBP Form 3461. Leading zeros must be shown. The check digit is computed on the previous 10 characters. The formula for calculating the check digit can be found in Appendix 1.
```

2023-05-17 20:09 UTC, TallTed commented on docs/openapi/components/schemas/credentials/EntryNumberCredential.yml
> +description: A credential which associates an customs entry number to a workflow.
```suggestion
description: A credential which associates a customs entry number to a workflow.
```

2023-05-22 09:12 UTC, nissimsan commented
@mkhraisha, ThingCred is added back. 

I don't know the detailed requirements going into a TFZ credential, so leaving that to you to model.  https://vocabulary.uncefact.org/LocationFunctionCodeList#273 seems like an applicable term.

2023-05-23 13:28 UTC, mkhraisha approved these changes

2023-05-23 18:05 UTC, BenjaminMoe approved these changes

2023-05-23 18:06 UTC, merged