Openapi Workflow
w3c-ccg/traceability-vocab pull request #797
Opened 2023-06-02 21:57 UTC by acarnagey

- Adds workflows to openapi paths
- Refactor paths into separate files

2023-06-06 17:36 UTC, BenjaminMoe approved these changes

2023-06-06 17:47 UTC, nissimsan commented
@acarnagey , could you add some more comments on this PR, pls? It isn't entirely clear on the call what is the effects of this.

2023-06-06 17:48 UTC, nissimsan commented
@acarnagey, suggestion to split this into two separate PRs.

2023-06-08 14:05 UTC, nissimsan commented
Also, @acarnagey, we recently removed the RDF classes from the respec: 

![image](https://github.com/w3c-ccg/traceability-vocab/assets/34443212/b546f586-3096-485c-b0ec-e8b1e5e418f9)

Can you please remove that in the PR?

2023-06-13 17:08 UTC, OR13 commented on docs/openapi/paths/workflows.yml
> +/schemas/workflows/businesscard.yml:
prefer kebab case here.

2023-06-13 17:10 UTC, OR13 commented on docs/openapi/paths/workflows.yml
> +/schemas/workflows/businesscard.yml:
```suggestion
/schemas/workflows/business-card-workflow.yml:
```

2023-06-13 17:34 UTC, acarnagey commented
Do not merge need to fix script that generates openapi.yml on npm i

2023-06-13 17:46 UTC, OR13 requested changes
Mark as draft, make CI pass, request a re-review

2023-06-13 19:46 UTC, OR13 commented on packages/traceability-schemas/services/schemas.js
> +const schemaKeys = ['common', 'credentials', 'presentations', 'snippets'];
these are "components", but that is a nit

2023-06-13 20:41 UTC, acarnagey commented
Closing this one out, the allOf in paths was causing additional validation errors

2023-06-13 20:41 UTC, closed without merging