Workflow cleanup
w3c-ccg/traceability-vocab pull request #855
Opened 2023-08-10 22:15 UTC by nissimsan

- adds `@id` for workflow to the context
- add a section with a resolvable anchor for the id
- removes the traceable presentation and workflow ymls with duplicate definitions

2023-08-11 08:20 UTC, nissimsan commented
Closes https://github.com/w3c-ccg/traceability-vocab/issues/852

2023-08-11 12:41 UTC, OR13 approved these changes

2023-08-11 17:56 UTC, TallTed requested changes
small, human-facing

2023-08-11 17:56 UTC, TallTed commented on docs/index.html
> +            A <code>TraceablePresentation</code> MAY be specify a <code>workflow</code>.
```suggestion
            A <code>TraceablePresentation</code> MAY specify a <code>workflow</code>. 
```

2023-08-15 16:14 UTC, mkhraisha approved these changes

2023-08-15 17:45 UTC, merged