Moving workflow NDR to vocab
w3c-ccg/traceability-vocab pull request #856
Opened 2023-08-25 10:58 UTC by nissimsan

Workflows were defined several places, both on interop and vocab. This takes a few of the good parts from interop, bringing it all together in one place.

2023-08-25 15:11 UTC, TallTed requested changes

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
> +            for example <code>https://w3id.org/traceability#us-cbp-entry</code>
```suggestion
            for example, <code>https://w3id.org/traceability#us-cbp-entry</code>.
```

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
> +            to the verifier the intention of making the presentation.
```suggestion
            to the verifier their intent to make the presentation.
```

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
> +            the intent of completing the workflow, participating parties, and required credential types.
```suggestion
            The Workflow Definition <em>SHOULD</em> resolve to a manifest file describing 
            the intent to complete the workflow, participating parties, and required credential types.
```

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
> +            for example <code>urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0</code>
```suggestion
            for example, <code>urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0</code>.
```

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
> +          <h4>Presentation Replace</h4>
```suggestion
          <h4>Presentation Replacement</h4>
```

2023-08-25 15:11 UTC, TallTed commented on docs/index.html
>  and MUST NOT be the same as any previous values presented.
```suggestion
and MUST NOT be the same as any previously presented values.
```

2023-08-29 17:36 UTC, OR13 approved these changes

2023-08-29 17:36 UTC, BenjaminMoe approved these changes

2023-08-29 17:36 UTC, merged