MX CFDI Invoice
w3c-ccg/traceability-vocab pull request #893
Opened 2023-10-24 17:02 UTC by BenjaminMoe

Narrowly defined VC version of MX CFDI v4.0 https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/mexico/electronic-invoicing

2023-10-25 13:32 UTC, nissimsan requested changes

2023-10-25 13:32 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/EInvoiceCredential.yml
> +title: e-Invoice Credential
This is based on specific Mexican requirements, I believe? I suggest we  reflected that from the title and description.

2023-10-25 13:32 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/EInvoiceCredential.yml
> +  term: EInvoiceCredential
MexicoEInvoiceCredential

2023-10-25 13:34 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/EInvoiceCredential.yml
> +  Narrowly defined specific invoice for steel
Include the link to the spec: 
MX CFDI v4.0 https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/mexico/electronic-invoicing

2023-10-26 14:34 UTC, nissimsan approved these changes

2023-10-26 19:09 UTC, OR13 approved these changes

2023-10-27 13:06 UTC, merged