delivery_and_injection_end_dates_update
w3c-ccg/traceability-vocab pull request #918
Opened 2023-12-13 19:00 UTC by Ralhusban

Updates in this PR:

Adjust `DeliverySchedule `/ `DeliveryScheduleCredential `to accomodate Injection / Delivery End dates as per industry requirement.

There was no need to update anything in the delivery ticket as it already contains open / close dates.

2023-12-13 22:15 UTC, TallTed requested changes

2023-12-13 22:15 UTC, TallTed commented on docs/openapi/components/schemas/common/DeliverySchedule.yml
>      description: The planned time for crude oil injection starts
```suggestion
    description: The planned time for crude oil injection to start
```

2023-12-13 22:15 UTC, TallTed commented on docs/openapi/components/schemas/common/DeliverySchedule.yml
> +    description: The planned time for crude oil injection ends
```suggestion
    description: The planned time for crude oil injection to end
```

2023-12-13 22:15 UTC, TallTed commented on docs/openapi/components/schemas/common/DeliverySchedule.yml
>      description: The planned time for crude oil delivery starts
```suggestion
    description: The planned time for crude oil delivery to start
```

2023-12-13 22:15 UTC, TallTed commented on docs/openapi/components/schemas/common/DeliverySchedule.yml
> +    description: The planned time for crude oil delivery ends
```suggestion
    description: The planned time for crude oil delivery to end
```

2023-12-14 00:02 UTC, Ralhusban reviewed
Thanks for the suggestions. All good for me

2023-12-14 14:45 UTC, mkhraisha approved these changes

2023-12-14 14:52 UTC, OR13 approved these changes

2023-12-14 14:54 UTC, BenjaminMoe approved these changes

2023-12-14 14:55 UTC, merged