BC Gov Petroleum And Natural Gas Title Credential
w3c-ccg/traceability-vocab pull request #930
Opened 2024-02-06 15:31 UTC by PatStLouis

This is a draft PR looking to align the BC Gov Energy and Mines Digital Trust framework with the traceability vocab to enable data exchanges. We are looking for feedback from both the traceability group on where these credentials would fit and the BC Gov EMDT governance team. 

[Here's the reference documentation](https://bcgov.github.io/bc-vcpedia/credentials/bc-petroleum-and-natural-gas-title/governance.html)

2024-02-06 18:33 UTC, TallTed requested changes

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      This field specifies the type of title based on the PNG Act. Title types can include the following: 1. Lease (Part 6); 2. Permit (Part 5); 3. Drilling Licence (Part 5.1), and 4. Storage Reservo
```suggestion
      This field specifies the type of title based on the PNG Act. Title types include the following: 1. Lease (Part 6); 2. Permit (Part 5); 3. Drilling Licence (Part 5.1), and 4. Storage Reservoir Licence (Part 14.130). Each title has only one title type.
```

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      The date when a title is issued, format is YYYY-MM-DD. Section 64 of the PNG Act
```suggestion
      The date when a title is issued, formatted as YYYY-MM-DD. Section 64 of the PNG Act
```

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      The date when the title becomes effective, format YYYY-MM-DD. This date usually follows after an issuance date and signals the start of a title period. This date does not change.
```suggestion
      The date when the title becomes effective, formatted as YYYY-MM-DD. This date usually follows an issuance date and signals the start of a title period. This date does not change.
```

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      This describes the length of time (term) granted for each title, expressed in YYYY. This date does not change.
```suggestion
      This describes the length of time (term) granted for each title, formatted as YYYY. This date does not change.
```

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      Expiry date is defined as effective date plus term, expressed as YYYY-MM-DD. This date signals the end of the title period.
```suggestion
      Expiry date is defined as effective date plus term, formatted as YYYY-MM-DD. This date signals the end of the title period.
```

2024-02-06 18:33 UTC, TallTed commented on docs/openapi/components/schemas/common/PetroleumAndNaturalGasTitle.yml
> +      The PNG Act describes a "holder of a location" as meaning "in accordance with the context, a permittee, licensee" . In this credential, the term title holder is used to reference a person in wh
```suggestion
      The PNG Act describes a "holder of a location" as meaning "in accordance with the context, a permittee, licensee". In this credential, the term "title holder" is used to reference a person in whose name a PNG title document is recorded in the division records. Title holders can be registered companies and/or persons. A Title Holder will hold a percentage (%) interest in the title. Percent interest defines the percentage of interest allotted to each party named in the PNG title document. Percentage of ownership can be divided up to eight digits and should always equal 100% total. Lessee is defined by the PNG Act as "a person in whose name a lease is recorded in the division records".
```

2024-03-19 10:24 UTC, nissimsan requested changes
Please update snake to camel case.

2024-03-19 10:24 UTC, nissimsan commented on docs/openapi/components/schemas/credentials/PetroleumAndNaturalGasTitleCredential.yml
> +      title_number:
snake_casing really burns my eyes... We use camelCase consistently everywhere else.

2024-03-19 13:42 UTC, PatStLouis commented
@nissimsan These attributes are taken directly from an existing published anoncreds schema. The camelCase/snake_case topic was brought to BC digital team and I'm looking at options such as redefining the schema using camelCase. Until I have agreement from the BC digital team I wouldn't feel comfortable merging this with camelCase. All of the current BC Verifiable Credentials use snake_case unfortunately, we might end up maintaining a separate context in the long run.

2024-04-18 19:05 UTC, mkhraisha commented
@PatStLouis has there been updates or movement here

2024-04-25 19:13 UTC, nissimsan commented
@PatStLouis , any progress on this?

2024-05-16 19:21 UTC, PatStLouis commented
@nissimsan I just received access to the Integrated Petroleum System. This will let me provide test values for an example and update the PR. We can expect an update in the next 2 weeks!

2024-06-13 19:07 UTC, PatStLouis commented
Closing this as BC Gov will pursue the UNTP Conformity Credential model for it's use case

2024-06-13 19:07 UTC, closed without merging