WebLEI credential
w3c-ccg/traceability-vocab pull request #968
Opened 2024-09-05 10:13 UTC by nissimsan

This adds a schema for a WebLEI credential, mainly wrapping the VC data model around the existing 3+ years old LEI classes: WebLEI for subject, LEIAuthority as issuer.

2024-09-10 23:28 UTC, brentzundel approved these changes

2024-09-11 18:57 UTC, TallTed requested changes

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/common/LEIAuthority.yml
> +    description: Issuing organization identifier, typically a Decentralized Identifier (DID).
```suggestion
    description: Identifier of the issuing organization , typically a Decentralized Identifier (DID).
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/common/LEIAuthority.yml
> +    description: Issuing organization name.
```suggestion
    description: Name of the issuing organization.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +  Level 1 Authority granting a Qualified WebLEI Issuer authority to issued WebLEI credentials.
```suggestion
  Level 1 Authority granting the authority to issue WebLEI credentials to a Qualified WebLEI Issuer.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: Issuing organization identifier, typically a Decentralized Identifier (DID).
```suggestion
        description: Identifier of the issuing organization, typically a Decentralized Identifier (DID).
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: Issuing organization name.
```suggestion
        description: Name of the issuing organization.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: The url of the schema file to validate the shape of the json object
```suggestion
        description: The URL of the schema file to be used to validate the shape of the JSON object.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: The type of validation to be run against the defined schema
```suggestion
        description: The type of validation to be run against the defined schema.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +    description: Qualified GLEIF approved Legal Entity Identifier issuer.
```suggestion
    description: Qualified GLEIF-approved issuer of Legal Entity Identifiers.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: Issuing organization identifier, typically a Decentralized Identifier (DID).
```suggestion
        description: Identifier of the issuing organization, typically a Decentralized Identifier (DID).
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/QualifiedWebLeiIssuerCredential.yml
> +        description: Issuing organization name.
```suggestion
        description: Name of the issuing organization.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/WebLeiCredential.yml
> +    description: Qualified GLEIF approved Legal Entity Identifier issuer.
```suggestion
    description: Qualified GLEIF-approved issuer of Legal Entity Identifiers.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/WebLeiCredential.yml
> +        description: Issuing organization identifier, typically a Decentralized Identifier (DID).
```suggestion
        description: Identifier of the issuing organization, typically a Decentralized Identifier (DID).
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/WebLeiCredential.yml
> +        description: Issuing organization name.
```suggestion
        description: Name of the issuing organization.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/WebLeiCredential.yml
> +        description: The url of the schema file to validate the shape of the json object
```suggestion
        description: The URL of the schema file to be used to validate the shape of the JSON object.
```

2024-09-11 18:57 UTC, TallTed commented on docs/openapi/components/schemas/credentials/WebLeiCredential.yml
> +        description: The type of validation to be run against the defined schema
```suggestion
        description: The type of validation to be run against the defined schema.
```

2024-09-12 17:03 UTC, mkhraisha approved these changes

2024-09-12 17:47 UTC, brentzundel approved these changes

2024-09-12 23:16 UTC, merged