Food Facility Registration schema
w3c-ccg/traceability-vocab pull request #969
Opened 2024-09-12 17:57 UTC by brentzundel

This PR adds a Food Facility Registration schema as required for the Ag Tech Demo 2024

2024-09-12 18:49 UTC, mkhraisha requested changes

2024-09-12 18:49 UTC, mkhraisha commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +  term: FFRCredential
Can we expand the name to be the full name not the acronym? I believe that's our current rule for all credential names

2024-09-12 18:50 UTC, mkhraisha commented
also seems to error on CI

2024-09-12 19:13 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +  term: FFRCredential
```suggestion
  term: FoodFacilityRegistraionCredential

```

2024-09-12 19:13 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +  '@id': https://w3id.org/traceability#FFRCredential
```suggestion
  '@id': https://w3id.org/traceability#FoodFacilityRegistrationCredential

```

2024-09-12 19:14 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +      - FFRCredential
```suggestion
      - FoodFacilityRegistrationCredential
    default:
      - VerifiableCredential
      - FoodFacilityRegistrationCredential

```

2024-09-12 19:14 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +        - FFRCredential
```suggestion
        - FoodFacilityRegistrationCredential

```

2024-09-12 19:16 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +        default: https://w3id.org/traceability/openapi/components/schemas/credentials/FFRCredential.yml
```suggestion
        example: https://w3id.org/traceability/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
        default: https://w3id.org/traceability/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
```

2024-09-12 19:17 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +    title: FFR
```suggestion
    title: Food Facility Registration
```

2024-09-12 19:18 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +      - type
```suggestion
```

2024-09-12 19:19 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +      "FFRCredential"
```suggestion
      "id": "https://w3id.org/traceability/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml"
    },
    "type": [
      "VerifiableCredential",
      "FoodFacilityRegistrationCredential"
```

2024-09-12 19:25 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +              - Null
None
```suggestion
              - None
```

2024-09-12 19:25 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +        "code": null
```suggestion
        "code": "None"
```

2024-09-12 19:25 UTC, brentzundel commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +      ],
```suggestion
```

2024-09-17 17:07 UTC, mkhraisha approved these changes

2024-09-17 21:02 UTC, TallTed requested changes
Tiny, human-facing

2024-09-17 21:02 UTC, TallTed commented on docs/openapi/components/schemas/credentials/FoodFacilityRegistrationCredential.yml
> +        description: The url of the schema file to be used to validate the shape of the JSON object
```suggestion
        description: The URL of the schema file to be used to validate the shape of the JSON object

```

2024-09-19 19:13 UTC, nissimsan approved these changes

2024-09-19 19:13 UTC, merged