Add Agriculture Credentials for Tech Demo
w3c-ccg/traceability-vocab pull request #972
Opened 2024-09-13 21:19 UTC by brentzundel

2024-09-16 18:41 UTC, TallTed requested changes
tiny, human-facing

2024-09-16 18:41 UTC, TallTed commented on docs/openapi/components/schemas/credentials/PhytosanitaryCredential.yml
> +        description: The url of the schema file to validate the shape of the json object
```suggestion
        description: The URL of the schema file to be used to validate the shape of the JSON object
```

2024-09-16 18:41 UTC, TallTed commented on docs/openapi/components/schemas/credentials/USDAPPQ203ForeignSiteInspectionCredential.yml
> +        description: The url of the schema file to validate the shape of the json object
```suggestion
        description: The URL of the schema file to be used to validate the shape of the JSON object
```

2024-09-17 17:08 UTC, mkhraisha approved these changes

2024-09-19 19:14 UTC, nissimsan approved these changes

2024-09-19 19:15 UTC, merged